# Generated by Django 2.1.5 on 2019-01-24 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=154, verbose_name='Description')),
                ('serial_number', models.CharField(max_length=20, verbose_name='Serial Number')),
                ('part_number', models.CharField(max_length=30, verbose_name='Part Number')),
                ('hardware_version', models.CharField(max_length=20, verbose_name='Hardware Version')),
                ('data_added', models.DateField(auto_now=True, verbose_name='Date Added')),
                ('location', models.CharField(max_length=20, verbose_name='Current Location')),
                ('invoice', models.CharField(max_length=20, verbose_name='Invoice')),
                ('is_usable_testing', models.BooleanField(verbose_name='Is Usable Testing')),
                ('comments', models.CharField(max_length=400, verbose_name='Comments')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='AndroidVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Danfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota_fiscal', models.CharField(max_length=10, verbose_name='No. NF')),
                ('data_emissao', models.DateField(verbose_name='Data Emissão')),
                ('data_entrada', models.DateField(auto_now=True, verbose_name='Data Entrada')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DanfeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254, verbose_name='Product Description')),
                ('ncm', models.CharField(max_length=20, verbose_name='NCM')),
                ('cst', models.SmallIntegerField(verbose_name='CST')),
                ('cfop', models.SmallIntegerField(verbose_name='CFOP')),
                ('qty', models.FloatField(verbose_name='Quantity')),
                ('danfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Danfe')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.IntegerField(verbose_name='Device ID')),
                ('is_usable', models.BooleanField(verbose_name='Is Usable')),
                ('public_name', models.CharField(max_length=150, verbose_name='Public Name')),
                ('internal_name', models.CharField(max_length=30, verbose_name='Internal Name')),
                ('serial_number', models.CharField(max_length=30, verbose_name='Serial Number')),
                ('ss_sd', models.CharField(max_length=2, verbose_name='SS/SD')),
                ('imei1', models.CharField(max_length=20, verbose_name='IMEI 1')),
                ('imei2', models.CharField(max_length=20, verbose_name='IMEI 2')),
                ('is_secure', models.BooleanField(verbose_name='Is Secure')),
                ('cid', models.SmallIntegerField(verbose_name='CID')),
                ('ram', models.CharField(max_length=30, verbose_name='RAM')),
                ('rom', models.CharField(max_length=30, verbose_name='ROM')),
                ('camera_frontal', models.CharField(max_length=30, verbose_name='Camera Frontal')),
                ('camera_rear', models.CharField(max_length=30, verbose_name='Camera Transeira')),
                ('is_nfc', models.BooleanField(verbose_name='NFC?')),
                ('is_fingerprint', models.BooleanField(verbose_name='Fingerprint?')),
                ('part_number', models.CharField(max_length=20, verbose_name='Part Number')),
                ('chipset', models.CharField(max_length=20, verbose_name='Chipset')),
                ('comment', models.CharField(max_length=400, verbose_name='Comments')),
                ('danfe', models.CharField(max_length=10, verbose_name='DANFE')),
                ('is_avaliable', models.BooleanField(verbose_name='Is Available')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('is_doogfooding', models.BooleanField(verbose_name='DoogFooding?')),
                ('android_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.AndroidVersion')),
                ('build', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Build')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=20, verbose_name='Zone')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Number')),
                ('pin1', models.CharField(max_length=4, verbose_name='PIN')),
                ('pin2', models.CharField(max_length=4, verbose_name='PIN2')),
                ('puk1', models.CharField(max_length=10, verbose_name='PUK')),
                ('puk2', models.CharField(max_length=10, verbose_name='PUK2')),
                ('iccid', models.CharField(max_length=30, verbose_name='ICCID')),
                ('comments', models.CharField(max_length=400, verbose_name='Comments')),
                ('is_account', models.BooleanField(verbose_name='Account?')),
                ('login', models.CharField(max_length=254, verbose_name='Login')),
                ('cloud_password', models.CharField(max_length=254, verbose_name='Cloud Password')),
                ('is_caller_name_id', models.BooleanField(verbose_name='Caller Name ID?')),
                ('is_vvm', models.BooleanField(verbose_name='VVM?')),
                ('is_volte', models.BooleanField(verbose_name='VOLTE?')),
                ('is_vowifi', models.BooleanField(verbose_name='VOWIFI')),
                ('is_hotspot', models.BooleanField(verbose_name='Hotspot')),
                ('vvm_password', models.CharField(max_length=254, verbose_name='VVM Password')),
                ('serial_number', models.CharField(max_length=30, verbose_name='Serial Number')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Carrier')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_test',
            field=models.CharField(max_length=200, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='simcard',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Team'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_situacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.DeviceStatus'),
        ),
        migrations.AddField(
            model_name='device',
            name='hardware_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.HardwareType'),
        ),
        migrations.AddField(
            model_name='device',
            name='sku_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.SkuType'),
        ),
        migrations.AddField(
            model_name='device',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Team'),
        ),
        migrations.AddField(
            model_name='device',
            name='user_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessory',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Team'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.AccessoryType'),
        ),
    ]
